#!/usr/bin/env bash
# The QA Test Automation (QATA) framework service
# Serves request on port 8421 (set below)

if [ $( id | sed -e 's/(.*//' ) != "uid=0" ]; then
  echo "Please rerun with super user privileges. "
  exit 1
fi

cid_file=/var/run/qata.pid
port=8421

project_dir=$(dirname $(readlink -f "$0"))
: ${SIS_TEST_DIR:=${project_dir}/test}
: ${DOCKER_NAMESPACE:=ucberkeley}
docker_image=${DOCKER_NAMESPACE}/sis-qa-test-auto

start() {
  if [ -f ${cid_file} ]; then
    container_id=$(cat ${cid_file})
    if [[ $(docker ps -a -q -f Id=${container_id}) ]]; then
      if [[ $(netstat -tulnp | grep ${port}) ]]; then
        echo "QATA already running. Not doing anything."
        return 1
      fi
      docker stop ${container_id} && docker rm ${container_id}
    fi
    rm -f ${cid_file}
  fi

  echo "Starting QATA..."
  docker inspect ${docker_image} &> /dev/null; if [ $? -ne 0 ]; then
    docker pull ${docker_image}
  fi

  container_id=$(docker run \
      --net=host \
      -t \
      -d \
      -e DISPLAY=${DISPLAY} \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      -v ${SIS_TEST_DIR}:/test \
      ${docker_image} \
      ${port})
  while ! [[ $(netstat -tulnp | grep ${port}) ]]; do
    sleep 1
  done
  echo ${container_id} > ${cid_file}
  echo "QATA started on port ${port}"
}

stop() {
  if [ ! -f ${cid_file} ]; then
    echo "QATA not running. Not doing anything."
    return 1
  fi

  echo "Stopping QATA..."
  container_id=$(cat ${cid_file})
  if [[ $(docker ps -q -f Id=${container_id}) ]]; then
    docker stop ${container_id} && docker rm ${container_id}
  fi
  rm -f ${cid_file}
  echo "QATA stopped..."
}

attach() {
  if [ ! -f ${cid_file} ]; then
    echo "QATA not running. Not doing anything."
    return 1
  fi

  container_id=$(cat ${cid_file})
  if ! [[ $(docker ps -a -q -f Id=${container_id}) ]] || ! [[ $(netstat -tulnp | grep 8421) ]]; then
    echo "QATA not running. Cleaning up."
    stop
    return 1
  fi

  docker attach --no-stdin ${container_id}
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  attach)
    attach
    ;;
  restart)
    stop
    start
    ;;
esac
