source 'https://rubygems.org'


# Use JSON for interpretting config file
gem 'json'

# Use Cucumber as DSL for browser tests
gem 'cucumber'

# Use Capybara to write step_definitions for Cucumber tests
gem 'capybara'

# Use Poltergeist (along with PhantomJS) as webdriver for Capybara
gem 'poltergeist'



