# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dashboard::Application.load_tasks

test_tasks = []

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)
  test_tasks.append :spec
rescue LoadError
  # no rspec available
end

task :default => test_tasks